#? Rules can be added here as most of the configuration are dynamic

# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Sizes for floating popups
windowrule = match:float 1, size <85% <95%
windowrule = match:tag common-popups, float on
windowrule = match:tag common-popups, size <60% <90%

# Fix file chooser dialogs opening off-screen
windowrule = match:tag portal-dialogs, float on
windowrule = match:tag portal-dialogs, center on

# Only add the Core applications here
windowrule = match:class ^(com.gabm.satty)$, float on
windowrule = match:class ^(org.kde.dolphin)$, match:title ^(Progress Dialog — Dolphin)$, float on
windowrule = match:class ^(org.kde.dolphin)$, match:title ^(Copying — Dolphin)$, float on
windowrule = match:title ^(About Mozilla Firefox)$, float on
windowrule = match:class ^(.*)$, match:initial_title ^(top)$, float on
windowrule = match:class ^(.*)$, match:initial_title ^(btop)$, float on
windowrule = match:class ^(.*)$, match:initial_title ^(htop)$, float on
windowrule = match:class ^(vlc)$, float on
windowrule = match:class ^(kvantummanager)$, float on
windowrule = match:class ^(qt5ct)$, float on
windowrule = match:class ^(qt6ct)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(nwg-displays)$, float on
windowrule = match:class ^(org.kde.ark)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-applet)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, float on

# common popups
windowrule = match:initial_title ^(Open File)$, tag +common-popups
windowrule = match:title ^(Choose Files)$, tag +common-popups
windowrule = match:title ^(Save As)$, tag +common-popups
windowrule = match:title ^(Confirm to replace files)$, tag +common-popups
windowrule = match:title ^(File Operation Progress)$, tag +common-popups
windowrule = match:class ^([Xx]dg-desktop-portal-gtk)$, tag +common-popups
windowrule = match:title ^(Open)$, tag +common-popups
windowrule = match:title ^(Authentication Required)$, tag +common-popups
windowrule = match:title ^(Add Folder to Workspace)$, tag +common-popups
windowrule = match:title ^(File Upload)(.*)$, tag +common-popups
windowrule = match:title ^(Choose wallpaper)(.*)$, tag +common-popups
windowrule = match:title ^(Library)(.*)$, tag +common-popups
windowrule = match:class ^(.*dialog.*)$, tag +common-popups
windowrule = match:title ^(.*dialog.*)$, tag +common-popups

# portal-dialogs
windowrule = match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$, tag +portal-dialogs
windowrule = match:class ^(org.freedesktop.impl.portal.desktop.gtk)$, tag +portal-dialogs
windowrule = match:class ^([Xx]dg-desktop-portal-gtk)$, tag +portal-dialogs


# // █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# // █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 1, match:namespace rofi
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 1, match:namespace notifications
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 1, match:namespace swaync-notification-window
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 1, match:namespace swaync-control-center
layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 1, match:namespace logout_dialog
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 1, match:namespace waybar
